### ISSUE TITLE
RHEL t3a.nano Returns error?

### ISSUE THREAD

**Issue by johnpetersjr** [mheffner/aws-pricing#17]
I tried using the function:

```EC2_RHEL_OD("t3a.nano","us-east-1") ```

And it returns back this error:

```Can not find instance type t2.nano of Rhel in us-east-1 (line 54).```

I also tried, for fun, t2.nano, and got the same error...

FYI - t3a.micro returns back a correct response.  Is there no lookup for RHEL Nano?

Looking up WINDOWS and LINUX On Demand pricing also worked fine for Nanos...

**Comment by mheffner** [comment]
Hi @johnpetersjr 

So I think the reason that you can't find a t3 or t2 nano sized instance for RHEL is that AWS don't seem to offer the RHEL instance in a t3.nano or t2.nano sized instance. If you check out the [pricing page](https://aws.amazon.com/ec2/pricing/on-demand/) and switch to RHEL, the smallest size I see is t3.micro. I also checked in the EC2 console and it does not allow me to launch a RHEL image on a nano instance.

Let me know if you find differently though.

Cheers!

**Comment by johnpetersjr** [comment]
That makes sense!  I create my own RHEL AMIs, and I guess AWS lets me downsize them to nano... I'll just use LINUX pricing for them I guess, close enough...

Thanks for this tool, it's awesome!
