### ISSUE TITLE
Provide instructions for local development and testing

### ISSUE THREAD

**Issue by deinspanjer** [mheffner/aws-pricing#18]
I am interested in possibly adding a couple of new service price lookup functions.  Is there any chance you could provide instructions for how to load up a clone of this repo in a local Google Sheets spreadsheet for testing?

**Comment by mheffner** [comment]
Hi @deinspanjer, that would be great to have! Yes, I'll take a stab at documenting the development process here to make it easier for others to test. Most of the development is based on the clasp environment: https://github.com/google/clasp. However, I'll write up more detailed steps.

**Comment by mheffner** [comment]
@deinspanjer Can you take a look at the steps here and see if you can reproduce them to get a working dev environment? https://github.com/mheffner/aws-pricing/blob/ecd747a44b409ee4a36376ade6de168752ab0dfc/DEVELOPMENT.md

**Comment by deinspanjer** [comment]
@mheffner thank you for putting that up.  I've been working on other stuff, but I read through the doc and I will be trying it out!
