### ISSUE TITLE
Argument too large: value (line 26).

### ISSUE THREAD

**Issue by ungarida** [mheffner/aws-pricing#24]
Hi there,
I had been using this Add-on for a while now but since today I'm getting on all `EC2` related function the error:

> Argument too large: value (line 26).

I tried multiple workarounds:
1. uninstall and re-install the add-on
2. modify existing spreadsheet
3. create a brand new spreadsheet

but nothing is working and I was not able to debug further the issue.

**Comment by mheffner** [comment]
Hi @ungarida , you're correct this is a bug. It looks like the pricing files have grown large enough that they no longer fit in the cache anymore. I'll need to dig in a bit and see if there's a way to shrink the file before caching.

**Comment by mheffner** [comment]
@ungarida I believe a new version should be published with a work-around for this. Let me know if this starts working for you over the next several hours. (GAS changed the publishing process since last time, so unsure if this went out or not)

**Comment by ungarida** [comment]
It works for me right now 👍
