### ISSUE TITLE
Can't get EBS Snapshot pricing

### ISSUE THREAD

**Issue by davidpurdue** [mheffner/aws-pricing#29]
Any call to EC2_EBS_SNAPSHOT_GB results in an error.

eg. EC2_EBS_SNAPSHOT_GB(1,"ap-southeast-1") gives "Error: Too many matches for EBS volume type null (line 50)."

**Comment by mheffner** [comment]
@davidpurdue Thanks for filing, I do see the same thing here (for other regions too). I'll find some time to debug this further, I don't have a handle on what's going on yet though.

**Comment by mheffner** [comment]
So it looks like this may be caused due to a combination of new Outpost EBS snapshot pricing and a poor type check on my part. Should be straightforward to fix and will get a patch in soon.

**Comment by mheffner** [comment]
@davidpurdue The fix should be deployed now and the release is propagating shortly. Let me know if you have any more issues.
