### ISSUE TITLE
App has been delisted from Google

### ISSUE THREAD

**Issue by trevormoseyeatstreet** [mheffner/aws-pricing#43]
The application has been delisted from Google Workspace, is this something that was intended?

**Comment by colemorgan** [comment]
Curious as well! This broke so many sheets!

**Comment by mheffner** [comment]
Oh no, apologies for this. Google alerted me that they would remove it if I didn't link to a privacy policy, but it was updated at least a week ago and I was under the impression it was now in compliance. I'm trying to identify how to get Google to relist this, but it may be a bit until I can get through to support.

**Comment by MigaFr** [comment]
Your app is really excellent, I'va been scared when I've seen that it disappear. Hope that you can fix it quick, knowing that google support isn't really ... fast/effective ... Good luck !

**Comment by mheffner** [comment]
Thanks! I found the marketplace page for the store listing and it was marked as "Rejected", but no reason was given. I've resubmitted it two days ago and it is now marked as "Under Review". 

UPDATE: It looks like it was just re-Approved and the link is working again. Can you give it another shot?

**Comment by MigaFr** [comment]
It works! excellent job, thank you :)

**Comment by mheffner** [comment]
Closing, hopefully we are set now. Thanks for reporting!
